name: tokoku
description: "A mobile app for managing grocery stores"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons and fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State management
  provider: ^6.1.2

  # Data storage
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2

  # Other useful libraries
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting for good coding practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
